//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsumerReservationHotel.RefWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceWebHotelSoap", Namespace="http://tp.umontpellier.fr/")]
    public partial class ServiceWebHotel : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReservationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAdressesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChambresOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchHotelOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceWebHotel() {
            this.Url = global::ConsumerReservationHotel.Properties.Settings.Default.ConsumerReservationHotel_RefWeb_ServiceWebHotel;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetHotelsCompletedEventHandler GetHotelsCompleted;
        
        /// <remarks/>
        public event GetReservationsCompletedEventHandler GetReservationsCompleted;
        
        /// <remarks/>
        public event GetAdressesCompletedEventHandler GetAdressesCompleted;
        
        /// <remarks/>
        public event GetClientsCompletedEventHandler GetClientsCompleted;
        
        /// <remarks/>
        public event GetCategoriesCompletedEventHandler GetCategoriesCompleted;
        
        /// <remarks/>
        public event GetChambresCompletedEventHandler GetChambresCompleted;
        
        /// <remarks/>
        public event SearchHotelCompletedEventHandler SearchHotelCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tp.umontpellier.fr/HelloWorld", RequestNamespace="http://tp.umontpellier.fr/", ResponseNamespace="http://tp.umontpellier.fr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tp.umontpellier.fr/GetHotels", RequestNamespace="http://tp.umontpellier.fr/", ResponseNamespace="http://tp.umontpellier.fr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hotel[] GetHotels() {
            object[] results = this.Invoke("GetHotels", new object[0]);
            return ((Hotel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelsAsync() {
            this.GetHotelsAsync(null);
        }
        
        /// <remarks/>
        public void GetHotelsAsync(object userState) {
            if ((this.GetHotelsOperationCompleted == null)) {
                this.GetHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelsOperationCompleted);
            }
            this.InvokeAsync("GetHotels", new object[0], this.GetHotelsOperationCompleted, userState);
        }
        
        private void OnGetHotelsOperationCompleted(object arg) {
            if ((this.GetHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelsCompleted(this, new GetHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tp.umontpellier.fr/GetReservations", RequestNamespace="http://tp.umontpellier.fr/", ResponseNamespace="http://tp.umontpellier.fr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Reservation[] GetReservations() {
            object[] results = this.Invoke("GetReservations", new object[0]);
            return ((Reservation[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReservationsAsync() {
            this.GetReservationsAsync(null);
        }
        
        /// <remarks/>
        public void GetReservationsAsync(object userState) {
            if ((this.GetReservationsOperationCompleted == null)) {
                this.GetReservationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReservationsOperationCompleted);
            }
            this.InvokeAsync("GetReservations", new object[0], this.GetReservationsOperationCompleted, userState);
        }
        
        private void OnGetReservationsOperationCompleted(object arg) {
            if ((this.GetReservationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReservationsCompleted(this, new GetReservationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tp.umontpellier.fr/GetAdresses", RequestNamespace="http://tp.umontpellier.fr/", ResponseNamespace="http://tp.umontpellier.fr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Adresse[] GetAdresses() {
            object[] results = this.Invoke("GetAdresses", new object[0]);
            return ((Adresse[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAdressesAsync() {
            this.GetAdressesAsync(null);
        }
        
        /// <remarks/>
        public void GetAdressesAsync(object userState) {
            if ((this.GetAdressesOperationCompleted == null)) {
                this.GetAdressesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdressesOperationCompleted);
            }
            this.InvokeAsync("GetAdresses", new object[0], this.GetAdressesOperationCompleted, userState);
        }
        
        private void OnGetAdressesOperationCompleted(object arg) {
            if ((this.GetAdressesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAdressesCompleted(this, new GetAdressesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tp.umontpellier.fr/GetClients", RequestNamespace="http://tp.umontpellier.fr/", ResponseNamespace="http://tp.umontpellier.fr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Client[] GetClients() {
            object[] results = this.Invoke("GetClients", new object[0]);
            return ((Client[])(results[0]));
        }
        
        /// <remarks/>
        public void GetClientsAsync() {
            this.GetClientsAsync(null);
        }
        
        /// <remarks/>
        public void GetClientsAsync(object userState) {
            if ((this.GetClientsOperationCompleted == null)) {
                this.GetClientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientsOperationCompleted);
            }
            this.InvokeAsync("GetClients", new object[0], this.GetClientsOperationCompleted, userState);
        }
        
        private void OnGetClientsOperationCompleted(object arg) {
            if ((this.GetClientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientsCompleted(this, new GetClientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tp.umontpellier.fr/GetCategories", RequestNamespace="http://tp.umontpellier.fr/", ResponseNamespace="http://tp.umontpellier.fr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Categorie[] GetCategories() {
            object[] results = this.Invoke("GetCategories", new object[0]);
            return ((Categorie[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCategoriesAsync() {
            this.GetCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void GetCategoriesAsync(object userState) {
            if ((this.GetCategoriesOperationCompleted == null)) {
                this.GetCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetCategories", new object[0], this.GetCategoriesOperationCompleted, userState);
        }
        
        private void OnGetCategoriesOperationCompleted(object arg) {
            if ((this.GetCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCategoriesCompleted(this, new GetCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tp.umontpellier.fr/GetChambres", RequestNamespace="http://tp.umontpellier.fr/", ResponseNamespace="http://tp.umontpellier.fr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Chambre[] GetChambres() {
            object[] results = this.Invoke("GetChambres", new object[0]);
            return ((Chambre[])(results[0]));
        }
        
        /// <remarks/>
        public void GetChambresAsync() {
            this.GetChambresAsync(null);
        }
        
        /// <remarks/>
        public void GetChambresAsync(object userState) {
            if ((this.GetChambresOperationCompleted == null)) {
                this.GetChambresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChambresOperationCompleted);
            }
            this.InvokeAsync("GetChambres", new object[0], this.GetChambresOperationCompleted, userState);
        }
        
        private void OnGetChambresOperationCompleted(object arg) {
            if ((this.GetChambresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChambresCompleted(this, new GetChambresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tp.umontpellier.fr/SearchHotel", RequestNamespace="http://tp.umontpellier.fr/", ResponseNamespace="http://tp.umontpellier.fr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseOfHotel SearchHotel(string ville, string nomHotel, System.DateTime dateArrivee, System.DateTime dateDebu, int prixMin, int prixMax, int nombreEtoile, int nombrePersonne) {
            object[] results = this.Invoke("SearchHotel", new object[] {
                        ville,
                        nomHotel,
                        dateArrivee,
                        dateDebu,
                        prixMin,
                        prixMax,
                        nombreEtoile,
                        nombrePersonne});
            return ((ResponseOfHotel)(results[0]));
        }
        
        /// <remarks/>
        public void SearchHotelAsync(string ville, string nomHotel, System.DateTime dateArrivee, System.DateTime dateDebu, int prixMin, int prixMax, int nombreEtoile, int nombrePersonne) {
            this.SearchHotelAsync(ville, nomHotel, dateArrivee, dateDebu, prixMin, prixMax, nombreEtoile, nombrePersonne, null);
        }
        
        /// <remarks/>
        public void SearchHotelAsync(string ville, string nomHotel, System.DateTime dateArrivee, System.DateTime dateDebu, int prixMin, int prixMax, int nombreEtoile, int nombrePersonne, object userState) {
            if ((this.SearchHotelOperationCompleted == null)) {
                this.SearchHotelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchHotelOperationCompleted);
            }
            this.InvokeAsync("SearchHotel", new object[] {
                        ville,
                        nomHotel,
                        dateArrivee,
                        dateDebu,
                        prixMin,
                        prixMax,
                        nombreEtoile,
                        nombrePersonne}, this.SearchHotelOperationCompleted, userState);
        }
        
        private void OnSearchHotelOperationCompleted(object arg) {
            if ((this.SearchHotelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchHotelCompleted(this, new SearchHotelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tp.umontpellier.fr/")]
    public partial class Hotel {
        
        private int idHotelField;
        
        private string nomHotelField;
        
        private int nombreChambreField;
        
        private int nombreLitField;
        
        private string lieuDitField;
        
        private int idCategorieField;
        
        /// <remarks/>
        public int IdHotel {
            get {
                return this.idHotelField;
            }
            set {
                this.idHotelField = value;
            }
        }
        
        /// <remarks/>
        public string nomHotel {
            get {
                return this.nomHotelField;
            }
            set {
                this.nomHotelField = value;
            }
        }
        
        /// <remarks/>
        public int nombreChambre {
            get {
                return this.nombreChambreField;
            }
            set {
                this.nombreChambreField = value;
            }
        }
        
        /// <remarks/>
        public int nombreLit {
            get {
                return this.nombreLitField;
            }
            set {
                this.nombreLitField = value;
            }
        }
        
        /// <remarks/>
        public string lieuDit {
            get {
                return this.lieuDitField;
            }
            set {
                this.lieuDitField = value;
            }
        }
        
        /// <remarks/>
        public int idCategorie {
            get {
                return this.idCategorieField;
            }
            set {
                this.idCategorieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tp.umontpellier.fr/")]
    public partial class ResponseOfHotel {
        
        private string messageField;
        
        private string codeField;
        
        private Hotel[] responsesField;
        
        private Adresse[] adressesField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public Hotel[] Responses {
            get {
                return this.responsesField;
            }
            set {
                this.responsesField = value;
            }
        }
        
        /// <remarks/>
        public Adresse[] adresses {
            get {
                return this.adressesField;
            }
            set {
                this.adressesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tp.umontpellier.fr/")]
    public partial class Adresse {
        
        private int idAdresseField;
        
        private int rueField;
        
        private string paysField;
        
        private int numeroField;
        
        private string villeField;
        
        private int idHotelField;
        
        private int gpsField;
        
        /// <remarks/>
        public int IdAdresse {
            get {
                return this.idAdresseField;
            }
            set {
                this.idAdresseField = value;
            }
        }
        
        /// <remarks/>
        public int Rue {
            get {
                return this.rueField;
            }
            set {
                this.rueField = value;
            }
        }
        
        /// <remarks/>
        public string Pays {
            get {
                return this.paysField;
            }
            set {
                this.paysField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Ville {
            get {
                return this.villeField;
            }
            set {
                this.villeField = value;
            }
        }
        
        /// <remarks/>
        public int IdHotel {
            get {
                return this.idHotelField;
            }
            set {
                this.idHotelField = value;
            }
        }
        
        /// <remarks/>
        public int Gps {
            get {
                return this.gpsField;
            }
            set {
                this.gpsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tp.umontpellier.fr/")]
    public partial class Chambre {
        
        private int idChambreField;
        
        private int prixField;
        
        private int nombreDeLietField;
        
        private bool estLibreField;
        
        private int idHotelField;
        
        /// <remarks/>
        public int IdChambre {
            get {
                return this.idChambreField;
            }
            set {
                this.idChambreField = value;
            }
        }
        
        /// <remarks/>
        public int Prix {
            get {
                return this.prixField;
            }
            set {
                this.prixField = value;
            }
        }
        
        /// <remarks/>
        public int NombreDeLiet {
            get {
                return this.nombreDeLietField;
            }
            set {
                this.nombreDeLietField = value;
            }
        }
        
        /// <remarks/>
        public bool EstLibre {
            get {
                return this.estLibreField;
            }
            set {
                this.estLibreField = value;
            }
        }
        
        /// <remarks/>
        public int IdHotel {
            get {
                return this.idHotelField;
            }
            set {
                this.idHotelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tp.umontpellier.fr/")]
    public partial class Categorie {
        
        private int idCategorieField;
        
        private int nombreEtoileField;
        
        private string nomCategorieField;
        
        /// <remarks/>
        public int IdCategorie {
            get {
                return this.idCategorieField;
            }
            set {
                this.idCategorieField = value;
            }
        }
        
        /// <remarks/>
        public int NombreEtoile {
            get {
                return this.nombreEtoileField;
            }
            set {
                this.nombreEtoileField = value;
            }
        }
        
        /// <remarks/>
        public string NomCategorie {
            get {
                return this.nomCategorieField;
            }
            set {
                this.nomCategorieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tp.umontpellier.fr/")]
    public partial class Client {
        
        private int idClientField;
        
        private string nomClientField;
        
        private string prenomClientField;
        
        private string infosPayementField;
        
        /// <remarks/>
        public int IdClient {
            get {
                return this.idClientField;
            }
            set {
                this.idClientField = value;
            }
        }
        
        /// <remarks/>
        public string NomClient {
            get {
                return this.nomClientField;
            }
            set {
                this.nomClientField = value;
            }
        }
        
        /// <remarks/>
        public string PrenomClient {
            get {
                return this.prenomClientField;
            }
            set {
                this.prenomClientField = value;
            }
        }
        
        /// <remarks/>
        public string InfosPayement {
            get {
                return this.infosPayementField;
            }
            set {
                this.infosPayementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tp.umontpellier.fr/")]
    public partial class Reservation {
        
        private int idReservationField;
        
        private int idClientField;
        
        private int prixReservationField;
        
        private int idChambreField;
        
        private System.DateTime dateDebutField;
        
        private System.DateTime dateFinField;
        
        /// <remarks/>
        public int IdReservation {
            get {
                return this.idReservationField;
            }
            set {
                this.idReservationField = value;
            }
        }
        
        /// <remarks/>
        public int IdClient {
            get {
                return this.idClientField;
            }
            set {
                this.idClientField = value;
            }
        }
        
        /// <remarks/>
        public int PrixReservation {
            get {
                return this.prixReservationField;
            }
            set {
                this.prixReservationField = value;
            }
        }
        
        /// <remarks/>
        public int IdChambre {
            get {
                return this.idChambreField;
            }
            set {
                this.idChambreField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateDebut {
            get {
                return this.dateDebutField;
            }
            set {
                this.dateDebutField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateFin {
            get {
                return this.dateFinField;
            }
            set {
                this.dateFinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetHotelsCompletedEventHandler(object sender, GetHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hotel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hotel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReservationsCompletedEventHandler(object sender, GetReservationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReservationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReservationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Reservation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Reservation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAdressesCompletedEventHandler(object sender, GetAdressesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAdressesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAdressesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Adresse[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Adresse[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetClientsCompletedEventHandler(object sender, GetClientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Client[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Client[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetCategoriesCompletedEventHandler(object sender, GetCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Categorie[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Categorie[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetChambresCompletedEventHandler(object sender, GetChambresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChambresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChambresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Chambre[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Chambre[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SearchHotelCompletedEventHandler(object sender, SearchHotelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchHotelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchHotelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseOfHotel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseOfHotel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591